name: 'Run claat'
description: 'Run claat tool to generate HTML files'
inputs:
  access-token: 
    description: 'Access Token'
    required: true
  doc-id:  
    description: 'Google Document Id'
    required: true  
runs:
  using: "composite"
  steps:
    - run: tools/claat-linux-amd64 export -auth ${{ inputs.access-token }} -o codelabs ${{ inputs.doc-id }}
      shell: bash