# This is a basic workflow to help you get started with Actions

name: Workflow Manual

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  claat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate key
        run: tools/go-generate-token -client=${{ secrets.clientId }} -secret=${{ secrets.clientId }} -refresh=${{ secrets.refreshToken }} 
      - name: Run claat
        run: tools/claat-linux-amd64 -h

