# This is a basic workflow to help you get started with Actions

name: Workflow Manual

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  claat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate key
        env:
          CLIENT_ID: ${{ secrets.clientId }}
          CLIENT_SECRET: ${{ secrets.clientSecret }}
          REFRESH_TOKEN: ${{ secrets.refreshToken }}
        run: |
          tools/go-generate-token -client=$CLIENT_ID -secret=$CLIENT_SECRET -refresh=$REFRESH_TOKEN > /tmp/token
          cat /tmp/token
      - name: Run claat
        run: tools/claat-linux-amd64 export -auth $(cat /tmp/token) 1siUvZ-ZuE5hS5EojiUuiVNJbQZ_R44Mf55SEEn13iDA
        

