# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Atualize Projeto 2
on:
  project_card:
    types: [created]

jobs:
  atualize:
    runs-on: ubuntu-latest
    steps:
      - name: Intro
        run: echo 1
        
      - name: Event info
        run: echo "${{ toJSON(github.event.project_card) }}"

      - name: Documentos
        env:
          PROJECT_CARD_NOTE: ${{ github.event.project_card.note }}
        run: |
          for Line in $PROJECT_CARD_NOTE
          do
            echo Google Doc: "$Line"
          done

      - uses: actions/checkout@v2

      - name: Generate key and run claat
        env:
          CLIENT_ID: ${{ secrets.clientId }}
          CLIENT_SECRET: ${{ secrets.clientSecret }}
          REFRESH_TOKEN: ${{ secrets.refreshToken }}
          PROJECT_CARD_NOTE: ${{ github.event.project_card.note }}
        run: |
          access_token=$(tools/go-generate-token -client=$CLIENT_ID -secret=$CLIENT_SECRET -refresh=$REFRESH_TOKEN)
          for Line in $PROJECT_CARD_NOTE
          do
            echo Processando "$Line"
            tools/claat-linux-amd64 export -auth $access_token -o codelabs "$Line"
          done

      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
