# This is a basic workflow to help you get started with Actions

name: Test Custom Action

on:
  workflow_dispatch:

jobs:
  claat:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/claat