# This is a basic workflow to help you get started with Actions

name: Test Custom Action

on:
  workflow_dispatch:

jobs:
  claat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/claat
        with:
          client-id: ${{ secrets.clientId }}
          client-secret: ${{ secrets.clientSecret }}
          refresh-token: ${{ secrets.refreshToken }}          
          doc-id: abc
